#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: frpc-conf
#data:
#  file.txt: |
#    <base64-encoded-content>
#---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: frp
  name: frpc
spec:
  serviceName: frpc
  replicas: 1
  selector:
    matchLabels:
      app: frpc
  template:
    metadata:
      labels:
        app: frpc
    spec:
      containers:
      - name: frpc
        image: registry.cn-hangzhou.aliyuncs.com/offends/vpn:frpc
        volumeMounts:
          - name: frpc-config
            mountPath: /frp
      volumes:
      - name: frpc-config
        configMap:
          name: frpc-conf
